#guarda historial

def guarda(nombre,n1,N1,n2,N2,longitudP,vocabularioP,volumenP,dificultadP,nivelP,esfuerzo,tiempo,numero):
    archivo=open(nombre,'r')
    historial=open('historial.txt','a')
    historial.write("NOMBRE DEL PROGRAMA :  ")
    historial.write(nombre)
    historial.write("\n")
    linea=archivo.readline()
    while linea!="":
        historial.write(linea)
        linea=archivo.readline()
    historial.write("\n\nMETRICAS BASICAs\n")
    historial.write("n1= ")
    historial.write(str(n1))
    historial.write("      N1= ")
    historial.write(str(N1))
    historial.write("      n2= ")
    historial.write(str(n2))
    historial.write("      N2= ")
    historial.write(str(N2))
    historial.write("\n\nMETRICAS DERIVADAS\n")
    historial.write("longitud del programa:  ")
    historial.write(str(longitudP))
    historial.write("\n")
    historial.write("vocabulario del programa")
    historial.write(str(vocabularioP))
    historial.write("\n")
    historial.write("volumen del programa")
    historial.write(str(volumenP))
    historial.write("\n")
    historial.write("dificultad del programa")
    historial.write(str(dificultadP))
    historial.write("\n")
    historial.write("nivel del programa")
    historial.write(str(nivelP))
    historial.write("\n")
    historial.write("esfuerzo de implementacion")
    historial.write(str(esfuerzo))
    historial.write("\n")
    historial.write("tiempo de implementacion")
    historial.write(str(tiempo))
    historial.write("\n")
    historial.write("numero de bugs liberados")
    historial.write(str(numero))
    historial.write("\n")
    historial.write("------------------------------------------------------------------------------------------------------------------------\n\n\n\n")
    archivo.close
    historial.close
